In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

# Linear Model

In [2]:
# # read the pickle file

# file=open("./taxi_fare_linear.pkl","rb")

In [3]:
# # load the model from the file
# model=pickle.load(file)

In [4]:
# file.close()

In [5]:
# val=np.array([[2, 2.10]])
# fares= model.predict(val)
# fares

# XG_Boost

In [6]:
# file_2=open("./taxi_fare_XG.pkl","rb")

In [7]:
# model_2=pickle.load(file_2)

In [8]:
# file_2.close()

In [9]:
# value=np.array([2.10])

In [10]:
# fares_2=model_2.predict(2.10)

In [11]:
# fares_2

# RANDOM FOREST

In [12]:
file_31=open("./taxi_fare_RANDOM1.pkl","rb")

In [13]:
file_32=open("./taxi_fare_RANDOM2.pkl","rb")

In [14]:
file_33=open("./taxi_fare_RANDOM3.pkl","rb")

In [15]:
model_31=pickle.load(file_31)

In [16]:
model_32=pickle.load(file_32)

In [17]:
model_33=pickle.load(file_33)

In [18]:
file_31.close()

In [19]:
file_32.close()

In [20]:
file_33.close()

In [21]:
model_31.predict([[2, 2.10]])

array([20.64950413])

In [22]:
model_32.predict([[2, 2.10]])

array([15.20450595])

In [23]:
model_33.predict([[2, 2.10]])

array([1.7808622])